services:
  emailservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice:v0.10.3
    ports:
      - "5000:8080"
    environment:
      - PORT=8080
      - DISABLE_PROFILER=1

  checkoutservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice:v0.10.3
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:5000
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070

  recommendationservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice:v0.10.3
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - DISABLE_PROFILER=1

  frontend:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend:v0.10.3
    ports:
      - "80:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - SHOPPING_ASSISTANT_SERVICE_ADDR=shoppingassistantservice:80
      - ENABLE_PROFILER=0

  paymentservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice:v0.10.3
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1

  productcatalogservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice:v0.10.3
    ports:
      - "3550:3550"
    environment:
      - PORT=3550
      - DISABLE_PROFILER=1

  cartservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.3
    ports:
      - "7070:7070"
    environment:
      - REDIS_ADDR=redis-cart:6379
    depends_on:
      - redis-cart

  redis-cart:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # loadgenerator:
  #   image: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator:v0.10.3
  #   environment:
  #     - FRONTEND_ADDR=frontend:8080
  #   depends_on:
  #     - frontend

  currencyservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice:v0.10.3
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - DISABLE_PROFILER=1

  shippingservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice:v0.10.3
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1

  adservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice:v0.10.3
    environment:
      - PORT=9555
      - DISABLE_PROFILER=1

volumes:
  redis-data: